apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}